import { NextRequest, NextResponse } from "next/server";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

// Target item counts: B01–B04=8, B05=7, B06/B07/B08/B12=10, B09=7, B10=8, B11=14
// Internal price bands (never shown to mothers): $100 Essentials, $175 Core, $250 Complete
const BUNDLES = [
  {
    code: "B01",
    name: "First Trimester Essentials",
    stage: "PREGNANCY" as const,
    description: "Everything a first-time mother needs during her pregnancy journey: vitamins, comfort aids, and reading material to prepare.",
    contentsMarkdown: [
      "- Prenatal multivitamin (90-day supply)",
      "- Pregnancy pillow",
      "- Stretch-mark cream (2×)",
      "- Belly band / maternity support belt",
      "- Pregnancy journal",
      "- *What to Expect When You're Expecting* book",
      "- Compression socks (1 pair)",
      "- Pregnancy-safe lip balm & skin care set",
    ].join("\n"),
    estimatedValue: 18000,
    priceBand: "CORE_175" as const,
    targetPriceCad: 175,
  },
  {
    code: "B02",
    name: "Second Trimester Comfort Kit",
    stage: "PREGNANCY" as const,
    description: "Targeted relief for the physical demands of pregnancy: swollen feet, back pain, and restless nights.",
    contentsMarkdown: [
      "- Compression socks (2 pairs)",
      "- Heating pad (back & belly safe)",
      "- Body pillow case (waterproof)",
      "- Cooling towel",
      "- Prenatal resistance band set",
      "- Lavender bath salts",
      "- Pregnancy-safe massage oil",
      "- Lumbar support wedge cushion",
    ].join("\n"),
    estimatedValue: 14000,
    priceBand: "CORE_175" as const,
    targetPriceCad: 175,
  },
  {
    code: "B03",
    name: "Third Trimester Preparation Kit",
    stage: "PREGNANCY" as const,
    description: "Nutritional support for mother and growing baby, including supplements and healthy snack options.",
    contentsMarkdown: [
      "- DHA / Omega-3 supplement",
      "- Iron supplement",
      "- Protein powder (pregnancy-safe)",
      "- Assorted healthy snack bars (24-pack)",
      "- Hydration electrolyte sachets (30-pack)",
      "- Insulated water bottle",
      "- Ginger chews for morning sickness (50-pack)",
      "- Prenatal probiotic (30-day supply)",
    ].join("\n"),
    estimatedValue: 12000,
    priceBand: "CORE_175" as const,
    targetPriceCad: 175,
  },
  {
    code: "B04",
    name: "Hospital Bag for Mother",
    stage: "LABOUR" as const,
    description: "Practical items to help mothers feel prepared and comfortable during labour and delivery.",
    contentsMarkdown: [
      "- Hospital bag checklist & organiser",
      "- Nursing-friendly robe",
      "- Non-slip socks (2 pairs)",
      "- Lip balm & toiletry kit",
      "- Snack bag for labour (granola bars, nuts, electrolytes)",
      "- Small speaker / white noise machine",
      "- Birth affirmation card set",
      "- Perineal cooling pads (20-pack)",
    ].join("\n"),
    estimatedValue: 10000,
    priceBand: "CORE_175" as const,
    targetPriceCad: 175,
  },
  {
    code: "B05",
    name: "Birth Partner Support Kit",
    stage: "LABOUR" as const,
    description: "Tools and comforts to help a birth partner provide meaningful support during labour.",
    contentsMarkdown: [
      "- Birth partner guide book",
      "- Massage roller & hand lotion",
      "- Comfort focal-point card set",
      "- Snacks for the support person",
      "- Cooling spray bottle",
      "- Hand-held mini fan",
      "- Encouraging messages card set",
    ].join("\n"),
    estimatedValue: 8000,
    priceBand: "ESSENTIALS_100" as const,
    targetPriceCad: 100,
  },
  {
    code: "B06",
    name: "Complete Newborn Bundle",
    stage: "NEWBORN" as const,
    description: "The absolute essentials a newborn needs in the first weeks of life.",
    contentsMarkdown: [
      "- Newborn onesies (6-pack, gender-neutral)",
      "- Swaddle blankets (3-pack)",
      "- Baby beanie & mittens set",
      "- Newborn nappies (pack of 48) ×2",
      "- Fragrance-free baby wipes (pack of 64)",
      "- Baby nail file set",
      "- Digital baby thermometer",
      "- Muslin burp cloths (4-pack)",
      "- Baby bath wash & lotion set",
      "- Baby hair brush & comb set",
    ].join("\n"),
    estimatedValue: 15000,
    priceBand: "CORE_175" as const,
    targetPriceCad: 175,
  },
  {
    code: "B07",
    name: "Newborn Sleep & Soothing Kit",
    stage: "NEWBORN" as const,
    description: "Help baby and mother get the rest they need with sleep aids and soothing essentials.",
    contentsMarkdown: [
      "- White noise machine",
      "- Baby sleep sack (0-3 months)",
      "- Swaddle wraps (2-pack)",
      "- Pacifiers (orthodontic, 2-pack)",
      "- Gripe water",
      "- Lavender-infused baby lotion",
      "- Infant gas drops",
      "- Blackout window clings (2-pack)",
      "- Baby massage oil (fragrance-free)",
      "- Nightlight with timer",
    ].join("\n"),
    estimatedValue: 13000,
    priceBand: "CORE_175" as const,
    targetPriceCad: 175,
  },
  {
    code: "B08",
    name: "Feeding Kit",
    stage: "NEWBORN" as const,
    description: "Support for breastfeeding and bottle-feeding through the early weeks.",
    contentsMarkdown: [
      "- Electric double breast pump",
      "- Breast pads (reusable, 8-pack)",
      "- Nipple cream",
      "- Bottle set (3 bottles with slow-flow nipples)",
      "- Bottle brush & drying rack",
      "- Nursing cover",
      "- Milk storage bags (50-pack)",
      "- Nursing bra (1)",
      "- Lactation support tea (30 bags)",
      "- Baby feeding pillow",
    ].join("\n"),
    estimatedValue: 20000,
    priceBand: "COMPLETE_250" as const,
    targetPriceCad: 250,
  },
  {
    code: "B09",
    name: "Postpartum Recovery Kit",
    stage: "POSTPARTUM" as const,
    description: "Essential recovery items to help mothers heal physically after childbirth.",
    contentsMarkdown: [
      "- Postpartum mesh underwear (10-pack)",
      "- Perineal spray",
      "- Sitz bath kit",
      "- Stool softener (gentle, 30-day)",
      "- Nipple shields",
      "- Peri bottle (postpartum hygiene)",
      "- Witch hazel pads (40-pack)",
    ].join("\n"),
    estimatedValue: 16000,
    priceBand: "ESSENTIALS_100" as const,
    targetPriceCad: 100,
  },
  {
    code: "B10",
    name: "Fourth Trimester Wellness Kit",
    stage: "POSTPARTUM" as const,
    description: "Resources and self-care items to support maternal mental health in the fourth trimester.",
    contentsMarkdown: [
      "- Postpartum wellness journal",
      "- Mindfulness meditation app gift card (3 months)",
      "- Herbal stress-relief tea (30 bags)",
      "- Self-care planner",
      "- *The Fourth Trimester* book",
      "- Affirmation card deck",
      "- Relaxing bath soak set",
      "- Calming soy candle",
    ].join("\n"),
    estimatedValue: 11000,
    priceBand: "CORE_175" as const,
    targetPriceCad: 175,
  },
  {
    code: "B11",
    name: "Maternal Nutrition & Recovery Bundle",
    stage: "POSTPARTUM" as const,
    description: "Nutritional support for recovery and breastfeeding in the months after birth.",
    contentsMarkdown: [
      "- Postnatal multivitamin (90-day supply)",
      "- Omega-3 supplement",
      "- Lactation tea (30 bags)",
      "- Lactation cookies (2 boxes)",
      "- Protein meal-replacement shakes (1-week supply)",
      "- Lactation protein powder (large tub, 30 servings)",
      "- Reusable snack bags",
      "- Iron supplement (postpartum)",
      "- Collagen peptides powder (30 servings)",
      "- Bone broth sachets (10-pack)",
      "- Nut & seed trail mix (500g)",
      "- Electrolyte drink mix (30-pack)",
      "- Postpartum belly wrap / binder",
      "- Postpartum meal prep guide",
    ].join("\n"),
    estimatedValue: 23000,
    priceBand: "COMPLETE_250" as const,
    targetPriceCad: 250,
  },
  {
    code: "B12",
    name: "Baby Development & Play Kit",
    stage: "NEWBORN" as const,
    description: "Stimulating and developmental toys for babies aged 0-6 months.",
    contentsMarkdown: [
      "- High-contrast black & white sensory cards",
      "- Soft sensory play mat",
      "- Rattles & teething rings set",
      "- Baby mirror toy",
      "- Board books (set of 4, 0-6 months)",
      "- Baby gym / activity arch",
      "- Soft stacking rings",
      "- Crinkle sensory toy",
      "- Baby musical shaker & drum set",
      "- Tummy time support pillow",
    ].join("\n"),
    estimatedValue: 17000,
    priceBand: "COMPLETE_250" as const,
    targetPriceCad: 250,
  },
];

export async function POST(req: NextRequest) {
  const admin = await requireAdmin(req);
  if (!admin) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const results = [];
  for (const b of BUNDLES) {
    const itemCount = b.contentsMarkdown.split("\n").filter((l) => l.startsWith("- ")).length;
    const bundle = await prisma.bundle.upsert({
      where: { code: b.code },
      update: {
        name: b.name,
        stage: b.stage,
        description: b.description,
        contentsMarkdown: b.contentsMarkdown,
        estimatedValue: b.estimatedValue,
        priceBand: b.priceBand,
        targetPriceCad: b.targetPriceCad,
      },
      create: {
        code: b.code,
        name: b.name,
        stage: b.stage,
        description: b.description,
        contentsMarkdown: b.contentsMarkdown,
        estimatedValue: b.estimatedValue,
        priceBand: b.priceBand,
        targetPriceCad: b.targetPriceCad,
        slotsPerMonth: 10,
        isActive: true,
      },
    });
    results.push({ code: bundle.code, name: bundle.name, itemCount });
  }

  return NextResponse.json({ seeded: results.length, bundles: results });
}
