-- Add email field to BundleApplication
ALTER TABLE "BundleApplication" ADD COLUMN "email" TEXT;

-- Add DELIVERED to BundleApplicationStatus enum
ALTER TYPE "BundleApplicationStatus" ADD VALUE 'DELIVERED';

-- Remove BUNDLE_GOAL_MET from NotifType enum
-- First purge any rows using the removed value (none expected)
DELETE FROM "Notification" WHERE type = 'BUNDLE_GOAL_MET';

-- Recreate enum via text cast pattern (Postgres cannot DROP ENUM VALUE directly)
ALTER TABLE "Notification" ALTER COLUMN "type" TYPE TEXT;
DROP TYPE "NotifType";
CREATE TYPE "NotifType" AS ENUM (
  'NEW_POST', 'REPLY', 'THREAD_REPLY', 'RBW_RESTRICTION', 'REPORT_CONFIRMED',
  'FULFILLMENT_PENDING', 'FULFILLMENT_CONFIRMED', 'FULFILLMENT_REMINDER',
  'BUNDLE_ALLOCATION_CONFIRM', 'ITEM_FULLY_FUNDED', 'ITEM_PURCHASED',
  'ITEM_DISPATCHED', 'ITEM_DELIVERED',
  'REQUEST_ACCEPTED', 'REQUEST_DECLINED', 'REQUEST_RECEIVED',
  'ITEM_RESERVED', 'ITEM_FULFILLED', 'DELIVERY_CONFIRMED', 'FULFILLMENT_DISPUTED',
  'BUNDLE_UPDATE', 'BUNDLE_DELIVERED',
  'ADMIN_MESSAGE', 'MODERATION_ACTION', 'VERIFICATION_APPROVED',
  'VERIFICATION_REJECTED', 'MANUAL_VERIFIED',
  'CIRCLE_REPLY', 'CIRCLE_THREAD_REPLY', 'CIRCLE_NEW_POST', 'CIRCLE_MILESTONE',
  'TRUST_MILESTONE', 'TRUST_WARNING', 'DONOR_LEVEL_UP',
  'REQUEST_LOCK_CLEARED',
  'COORDINATION_ACCEPTED', 'COORDINATION_TIME_PROPOSED', 'COORDINATION_SCHEDULED',
  'COORDINATION_CANCELLED', 'COORDINATION_DELIVERED',
  'REGISTER_ITEM_APPROVED', 'REGISTER_ITEM_REJECTED',
  'ADDRESS_REMINDER', 'ADDRESS_TIMEOUT_CANCELLED',
  'BUNDLE_DISPATCHED',
  'BUNDLE_APPLICATION_APPROVED', 'BUNDLE_APPLICATION_REJECTED'
);
ALTER TABLE "Notification" ALTER COLUMN "type" TYPE "NotifType" USING "type"::"NotifType";
