ALTER TYPE "RegisterItemStatus" ADD VALUE IF NOT EXISTS 'AWAITING_ADDRESS';
ALTER TYPE "RegisterItemStatus" ADD VALUE IF NOT EXISTS 'AWAITING_PURCHASE';
ALTER TYPE "NotifType" ADD VALUE IF NOT EXISTS 'ADDRESS_REMINDER';
ALTER TYPE "NotifType" ADD VALUE IF NOT EXISTS 'ADDRESS_TIMEOUT_CANCELLED';
